#!/usr/bin/env bash
# __        ______    _____  __  __           _
# \ \      / /  _ \  | ____|/ _|/ _| ___  ___| |_ ___
#  \ \ /\ / /| |_) | |  _| | |_| |_ / _ \/ __| __/ __|
#   \ V  V / |  __/  | |___|  _|  _|  __/ (__| |_\__ \
#    \_/\_/  |_|     |_____|_| |_|  \___|\___|\__|___/
#

# Notifications
source "$HOME/.config/ml4w/scripts/ml4w-notification-handler"
APP_NAME="Waypaper"
NOTIFICATION_ICON="preferences-desktop-wallpaper-symbolic"

ml4w_cache_folder="$HOME/.cache/ml4w/hyprland-dotfiles"

# Get current wallpaper
cache_file="$ml4w_cache_folder/current_wallpaper"

# Options for the wallpaper effects
options="$(ls ~/.config/hypr/effects/wallpaper/)\noff"

# Open launcher
choice=$(echo -e "$options" | $HOME/.config/ml4w/scripts/ml4w-launcher dmenu -p "Wallpaper effect" -l 5 --rofi-args "-no-show-icons -width 30")
if [ ! -z $choice ]; then
    echo "$choice" > "$HOME/.config/ml4w/settings/wallpaper-effect"
    $HOME/.config/ml4w/scripts/ml4w-wallpaper "$(cat $cache_file)"
fi
