#!/usr/bin/env bash
#   ____ _ _       _     _     _
#  / ___| (_)_ __ | |__ (_)___| |_
# | |   | | | '_ \| '_ \| / __| __|
# | |___| | | |_) | | | | \__ \ |_
#  \____|_|_| .__/|_| |_|_|___/\__|
#           |_|
#
# -----------------------------------------------------
# Load Launcher
# -----------------------------------------------------
launcher=$(cat $HOME/.config/ml4w/settings/launcher)
if [ "$launcher" == "walker" ] && command -v walker >/dev/null 2>&1; then
    walker -t ml4w -m clipboard -N -H
else
    case $1 in
        d)
            selected=$(cliphist list | rofi -dmenu -replace -config ~/.config/rofi/config-cliphist.rasi)
            [ -z "$selected" ] && exit 0
            echo "$selected" | cliphist delete
        ;;
        w)
            cliphist wipe
        ;;
        *)
            selected=$(cliphist list | rofi -dmenu -replace -config ~/.config/rofi/config-cliphist.rasi)
            [ -z "$selected" ] && exit 0
            echo "$selected" | cliphist decode | wl-copy
        ;;
    esac
fi