#!/usr/bin/env bash
echo ":: The script will install the ML4W Hyprland Settings app."
echo ":: Please note: The app requires Flatpak."
if gum confirm "Do you want to proceed?"; then
    ml4w_app="com.ml4w.hyprlandsettings"
    ml4w_app_repo="hyprland-settings"
    echo ":: Installing $ml4w_app"
    bash -c "$(curl -s https://raw.githubusercontent.com/mylinuxforwork/$ml4w_app_repo/master/setup.sh)"
fi