#!/bin/bash
#  __  __ _    _  ___        __  ____        _    __ _ _           
# |  \/  | |  | || \ \      / / |  _ \  ___ | |_ / _(_) | ___  ___ 
# | |\/| | |  | || |\ \ /\ / /  | | | |/ _ \| __| |_| | |/ _ \/ __|
# | |  | | |__|__   _\ V  V /   | |_| | (_) | |_|  _| | |  __/\__ \
# |_|  |_|_____| |_|  \_/\_/    |____/ \___/ \__|_| |_|_|\___||___/
#                                                                 
# for Hyprland

# ----------------------------------------------------- 
# Installation
# -----------------------------------------------------

source_directory="$(dirname $(pwd))"
source_bin_directory="$source_directory/bin"
source_share_directory="$source_directory/share"
source_lib_directory="$source_directory/lib"

package_name="ml4w-hyprland"
base_directory="/usr"
bin_directory="$base_directory/bin"
share_directory="$base_directory/share/$package_name"
lib_directory="$base_directory/lib/$package_name"

sudo cp $source_bin_directory/ml4w-hyprland-setup $bin_directory
echo ":: $source_bin_directory/ml4w-hyprland-setup installed"

sudo cp $source_share_directory/. $share_directory
echo ":: $share_directory installed"

sudo cp $source_lib_directory/. $lib_directory 
echo ":: $lib_directory installed"

echo 

echo ":: Please run the command ml4w-hyprland-setup"