packages=(
    "fastfetch"
    "eza" 
    "python-pip" 
    "python3-gobject"
    "python-screeninfo"
    "tumbler" 
    "brightnessctl"
    "nm-connection-editor"
    "network-manager-applet"
    "gtk4"
    "libadwaita"
    "fuse"
    "ImageMagick"
    "jq"
    "xclip"    
    "firefox"
    "kitty"
    "neovim"
    "htop"
    "nautilus"
#    "nautilus-open-any-terminal"
    "python-pywal"
    "pinta"
    "blueman"
    "grim" 
    "slurp"
    "cliphist"
    # "nwg-look"
    "qt6ct"
    "waybar" 
    "rofi-wayland"
    # "polkit-gnome"
    "zsh"
    # "zsh-completions"
    "fzf"
    "pavucontrol" 
    "papirus-icon-theme"
    "breeze"
    "gvfs"
    "wlogout"
    "hyprshade"
    "waypaper"
    "grimblast-git"
    "aylurs-gtk-shell"
    "bibata-cursor-theme"
    "fontawesome-6-free-fonts" 
    "mozilla-fira-sans-fonts" 
    "fira-code-fonts" 
    # "ttf-firacode-nerd" 
);
